### ISSUE TITLE
Unable to open characters in V10 Prototype 3

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#355]
Click the character, nothing happens. Error log:

Foundry VTT | Rendering DCCActorSheetCleric
commons.js:4889 Error: You are accessing the DCCActor#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:4878:19)
    at Function._logV10CompatibilityWarning (commons.js:5716:14)
    at DCCActor.get data [as data] (commons.js:5616:24)
    at DCCActorSheetCleric.getData (actor-sheet.js:60:28)
    at DCCActorSheetCleric.getData (actor-sheets-dcc.js:16:24)
    at DCCActorSheetCleric._render (foundry.js:4102:29)
    at DCCActorSheetCleric._render (foundry.js:4826:17)
    at DCCActorSheetCleric.render (foundry.js:4061:10)
    at DCCActorSheetCleric.render (foundry.js:5324:18)
    at ActorDirectory._onClickDocumentName (foundry.js:52625:16)
logCompatibilityWarning @ commons.js:4889
_logV10CompatibilityWarning @ commons.js:5716
get data @ commons.js:5616
getData @ actor-sheet.js:60
getData @ actor-sheets-dcc.js:16
_render @ foundry.js:4102
_render @ foundry.js:4826
render @ foundry.js:4061
render @ foundry.js:5324
_onClickDocumentName @ foundry.js:52625
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
commons.js:4889 Error: You are accessing the DCCActor#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:4878:19)
    at Function._logV10CompatibilityWarning (commons.js:5716:14)
    at DCCActor.get data [as data] (commons.js:5616:24)
    at DCCActorSheetCleric.getData (actor-sheet.js:61:27)
    at DCCActorSheetCleric.getData (actor-sheets-dcc.js:16:24)
    at DCCActorSheetCleric._render (foundry.js:4102:29)
    at DCCActorSheetCleric._render (foundry.js:4826:17)
    at DCCActorSheetCleric.render (foundry.js:4061:10)
    at DCCActorSheetCleric.render (foundry.js:5324:18)
    at ActorDirectory._onClickDocumentName (foundry.js:52625:16)
logCompatibilityWarning @ commons.js:4889
_logV10CompatibilityWarning @ commons.js:5716
get data @ commons.js:5616
getData @ actor-sheet.js:61
getData @ actor-sheets-dcc.js:16
_render @ foundry.js:4102
_render @ foundry.js:4826
render @ foundry.js:4061
render @ foundry.js:5324
_onClickDocumentName @ foundry.js:52625
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
commons.js:4889 Error: You are accessing the DCCActor#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:4878:19)
    at Function._logV10CompatibilityWarning (commons.js:5716:14)
    at DCCActor.get data [as data] (commons.js:5616:24)
    at DCCActorSheetCleric.getData (actor-sheet.js:62:29)
    at DCCActorSheetCleric.getData (actor-sheets-dcc.js:16:24)
    at DCCActorSheetCleric._render (foundry.js:4102:29)
    at DCCActorSheetCleric._render (foundry.js:4826:17)
    at DCCActorSheetCleric.render (foundry.js:4061:10)
    at DCCActorSheetCleric.render (foundry.js:5324:18)
    at ActorDirectory._onClickDocumentName (foundry.js:52625:16)
logCompatibilityWarning @ commons.js:4889
_logV10CompatibilityWarning @ commons.js:5716
get data @ commons.js:5616
getData @ actor-sheet.js:62
getData @ actor-sheets-dcc.js:16
_render @ foundry.js:4102
_render @ foundry.js:4826
render @ foundry.js:4061
render @ foundry.js:5324
_onClickDocumentName @ foundry.js:52625
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
commons.js:4889 Error: You are accessing DCCActor#data which has been migrated to DCCActor#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:4878:19)
    at Function._logDataFieldMigration (commons.js:5705:14)
    at Object.get (commons.js:5669:18)
    at DCCActorSheetCleric.getData (actor-sheet.js:62:34)
    at DCCActorSheetCleric.getData (actor-sheets-dcc.js:16:24)
    at DCCActorSheetCleric._render (foundry.js:4102:29)
    at DCCActorSheetCleric._render (foundry.js:4826:17)
    at DCCActorSheetCleric.render (foundry.js:4061:10)
    at DCCActorSheetCleric.render (foundry.js:5324:18)
    at ActorDirectory._onClickDocumentName (foundry.js:52625:16)
logCompatibilityWarning @ commons.js:4889
_logDataFieldMigration @ commons.js:5705
get @ commons.js:5669
getData @ actor-sheet.js:62
getData @ actor-sheets-dcc.js:16
_render @ foundry.js:4102
_render @ foundry.js:4826
render @ foundry.js:4061
render @ foundry.js:5324
_onClickDocumentName @ foundry.js:52625
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
commons.js:4889 Error: You are accessing the DCCActor#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:4878:19)
    at Function._logV10CompatibilityWarning (commons.js:5716:14)
    at DCCActor.get data [as data] (commons.js:5616:24)
    at DCCActorSheetCleric.getData (actor-sheet.js:63:27)
    at DCCActorSheetCleric.getData (actor-sheets-dcc.js:16:24)
    at DCCActorSheetCleric._render (foundry.js:4102:29)
    at DCCActorSheetCleric._render (foundry.js:4826:17)
    at DCCActorSheetCleric.render (foundry.js:4061:10)
    at DCCActorSheetCleric.render (foundry.js:5324:18)
    at ActorDirectory._onClickDocumentName (foundry.js:52625:16)
logCompatibilityWarning @ commons.js:4889
_logV10CompatibilityWarning @ commons.js:5716
get data @ commons.js:5616
getData @ actor-sheet.js:63
getData @ actor-sheets-dcc.js:16
_render @ foundry.js:4102
_render @ foundry.js:4826
render @ foundry.js:4061
render @ foundry.js:5324
_onClickDocumentName @ foundry.js:52625
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
commons.js:4889 Error: You are accessing the DCCActor#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:4878:19)
    at Function._logV10CompatibilityWarning (commons.js:5716:14)
    at DCCActor.get data [as data] (commons.js:5616:24)
    at DCCActorSheetCleric.getData (actor-sheet.js:67:42)
    at DCCActorSheetCleric.getData (actor-sheets-dcc.js:16:24)
    at DCCActorSheetCleric._render (foundry.js:4102:29)
    at DCCActorSheetCleric._render (foundry.js:4826:17)
    at DCCActorSheetCleric.render (foundry.js:4061:10)
    at DCCActorSheetCleric.render (foundry.js:5324:18)
    at ActorDirectory._onClickDocumentName (foundry.js:52625:16)
logCompatibilityWarning @ commons.js:4889
_logV10CompatibilityWarning @ commons.js:5716
get data @ commons.js:5616
getData @ actor-sheet.js:67
getData @ actor-sheets-dcc.js:16
_render @ foundry.js:4102
_render @ foundry.js:4826
render @ foundry.js:4061
render @ foundry.js:5324
_onClickDocumentName @ foundry.js:52625
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
commons.js:4889 Error: You are accessing the DCCActor#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:4878:19)
    at Function._logV10CompatibilityWarning (commons.js:5716:14)
    at DCCActor.get data [as data] (commons.js:5616:24)
    at DCCActorSheetCleric.getData (actor-sheet.js:68:41)
    at DCCActorSheetCleric.getData (actor-sheets-dcc.js:16:24)
    at DCCActorSheetCleric._render (foundry.js:4102:29)
    at DCCActorSheetCleric._render (foundry.js:4826:17)
    at DCCActorSheetCleric.render (foundry.js:4061:10)
    at DCCActorSheetCleric.render (foundry.js:5324:18)
    at ActorDirectory._onClickDocumentName (foundry.js:52625:16)
logCompatibilityWarning @ commons.js:4889
_logV10CompatibilityWarning @ commons.js:5716
get data @ commons.js:5616
getData @ actor-sheet.js:68
getData @ actor-sheets-dcc.js:16
_render @ foundry.js:4102
_render @ foundry.js:4826
render @ foundry.js:4061
render @ foundry.js:5324
_onClickDocumentName @ foundry.js:52625
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
commons.js:4889 Error: You are accessing DCCActor#data which has been migrated to DCCActor#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:4878:19)
    at Function._logDataFieldMigration (commons.js:5705:14)
    at Object.get (commons.js:5669:18)
    at DCCActorSheetCleric.getData (actor-sheet.js:68:46)
    at DCCActorSheetCleric.getData (actor-sheets-dcc.js:16:24)
    at DCCActorSheetCleric._render (foundry.js:4102:29)
    at DCCActorSheetCleric._render (foundry.js:4826:17)
    at DCCActorSheetCleric.render (foundry.js:4061:10)
    at DCCActorSheetCleric.render (foundry.js:5324:18)
    at ActorDirectory._onClickDocumentName (foundry.js:52625:16)
logCompatibilityWarning @ commons.js:4889
_logDataFieldMigration @ commons.js:5705
get @ commons.js:5669
getData @ actor-sheet.js:68
getData @ actor-sheets-dcc.js:16
_render @ foundry.js:4102
_render @ foundry.js:4826
render @ foundry.js:4061
render @ foundry.js:5324
_onClickDocumentName @ foundry.js:52625
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:386 TypeError: Cannot set properties of undefined (setting 'img')
    at DCCActorSheetCleric.getData (actor-sheet.js:73:27)
    at DCCActorSheetCleric.getData (actor-sheets-dcc.js:16:24)
    at DCCActorSheetCleric._render (foundry.js:4102:29)
    at DCCActorSheetCleric._render (foundry.js:4826:17)
    at DCCActorSheetCleric.render (foundry.js:4061:10)
    at DCCActorSheetCleric.render (foundry.js:5324:18)
    at ActorDirectory._onClickDocumentName (foundry.js:52625:16)
    at HTMLOListElement.dispatch (jquery.min.js:2:43064)
    at HTMLOListElement.v.handle (jquery.min.js:2:41048)

**Comment by mooped** [comment]
Sheets now open on the v10 branch (v0.34.0 ).
