### ISSUE TITLE
Player with can not open another players character sheet if they have Observer permissions

### ISSUE THREAD

**Issue by gabecook** [foundryvtt-dcc/dcc#459]
Previously, my players could look at each other's sheets if they had observer permissions on those players' actors. 

As the GM I can look at the sheets.

When I log in as a player, I cannot open another players sheet, even with Observer permissions. Looking in the console, I see this error:

```
foundry.js:655 Error: An error occurred while rendering DCCActorSheetHalfling 28. Cannot set properties of undefined (setting 'tooltip')
[Detected 1 package: system:dcc(0.50.24)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at foundry.js:5795:13Caused by: TypeError: Cannot set properties of undefined (setting 'tooltip')
[Detected 1 package: system:dcc(0.50.24)]
    at DCCActorSheetHalfling._getHeaderButtons (actor-sheet.js:52:24)
    at DCCActorSheetHalfling._renderOuter (foundry.js:5970:27)
    at DCCActorSheetHalfling._renderOuter (foundry.js:7168:30)
    at DCCActorSheetHalfling._render (foundry.js:5855:27)
    at async DCCActorSheetHalfling._render (foundry.js:6572:5)
    at async DCCActorSheetHalfling._render (foundry.js:7158:5)
```

![image](https://github.com/user-attachments/assets/f6aa139f-b99d-4a6a-8b52-3d83ed157aae)

**Comment by cyface** [comment]
Thanks for the detailed report! I don't usually set things up like you are suggesting, so I am not totally sure I fixed this, but I think I did based on your description. Try v0.50.26 and see if that does the trick.

**Comment by gabecook** [comment]
Thank you @cyface! I just tested it and it looks good.
